apiVersion: apps/v1
kind: Deployment
metadata:
  name: dop-deployment
  namespace: dop-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dop-deployment
  template:
    metadata:
      labels:
        app: dop-deployment
    spec:
      imagePullSecrets:
        - name: dop-token
      containers:
        - name: dop-deployment
          image: mickyma22/my-repo:complete-project-5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
