apiVersion: v1
kind: Service
metadata:
  name: dop-deployment-service
  namespace: dop-namespace
spec:
  type: NodePort
  selector:
    app: dop-deployment
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000
